### ISSUE TITLE
UI is displayed in a Slavic language

### ISSUE THREAD

**Issue by heviiguy** [house-of-abbey/GarminHomeAssistant#194]
**Describe the bug**

Rather than the Garmin Express settings for the app being displayed in English as all of my other settings are, the UI is displayed in a Slavic language

I have:

- [x] Used HTTPS to access HomeAssistant (with a public certificate)
- [x] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [x] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [x] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**

1. Go to '.Garmin Express.'
2. Click on '.GarminHomeAssistant(application)..'
3. Scroll down to '."three dots"...'

**Expected behavior**
English UI

**Screenshots**
GarminHomeAssistant:
<img width="503" alt="Screenshot 2024-11-03 at 12 28 26" src="https://github.com/user-attachments/assets/dc09cbf0-3d19-4ded-a2f0-98abee3f0aec">

<img width="503" alt="Screenshot 2024-11-03 at 12 32 15" src="https://github.com/user-attachments/assets/5e039c8b-4ee1-4ce7-bce4-aa430fcee2b1">

Typical:
<img width="501" alt="Screenshot 2024-11-03 at 12 33 45" src="https://github.com/user-attachments/assets/236ff3e5-237a-405f-b4f1-4a4d9182a25c">

**Garmin Device (please complete the following information):**

- Model: [Fenix 6 Pro]

**Additional context**
In "Garmin Express" when attempting to set-up the application

**Comment by philipabbey** [comment]
Because the other apps don't offer Slavic translations?

**Comment by heviiguy** [comment]
> Because the other apps don't offer Slavic translations?

No idea. I only know that I've not selected the UI to be in this language. I have absolutely no idea what the selection boxes refer to!

**Comment by heviiguy** [comment]
Seems that this is not an isolated issue...

https://forums.garmin.com/developer/connect-iq/i/bug-reports/garmin-express---wrong-language

**Comment by philipabbey** [comment]
And this bug is not consistent either. I can't recreate it with Garmin Express Ver 7.20.3.0.

![image](https://github.com/user-attachments/assets/e295e3a1-0577-4af5-811b-e9fffb288dff)

Thank you so much for your investigation to track down those two links above. In the case of this app, we do not create `resources-eng` as a copy of the default. This point relates to both links that suggests we ought to, but then another user says that workaround did not work. We're then left with the inconsistency issue which means I cannot test for a fix even if I do repeat the `resources-eng\strings\strings.xml` file.

Now I've avoided updating Garmin Express since I use the mobile app instead, and its a pain to keep the Windoze desktop PC updated all the time (the application must be installed on a proper Admin account not just with elevated priviledges or things go wrong as I recall).

Do you need me to provide a trial installer with the default strings copied to `resources-eng` for you to sideload and try?

**Comment by heviiguy** [comment]
Thanks for your comments, @philipabbey.  And thanks for your offer of the trial installer. Alas, I've not a clue of how I'd go about sideloading it 🤪. What would be much easier, I think, is to just show me (and anybody else suffering from this issue) a couple of screen shots showing the settings comments in English. That way I (we) can enter the relevant data and get this puppy running!

**Comment by philipabbey** [comment]
> Thanks for your comments, @philipabbey.  And thanks for your offer of the trial installer. Alas, I've not a clue of how I'd go about sideloading it 🤪. What would be much easier, I think, is to just show me (and anybody else suffering from this issue) a couple of screen shots showing the settings comments in English. That way I (we) can enter the relevant data and get this puppy running!

Please see the documentation here:

https://github.com/house-of-abbey/GarminHomeAssistant#settings

**Comment by heviiguy** [comment]
Got it. Thank-you very much, Phillip!

**Comment by philipabbey** [comment]
I'm going to close this issue on the grounds that there's a bug in Garmin Express that I cannot resolve. Thanks for taking the time to report and then research the issue, very helpful! I might add a note to the Known Issues section of the documentation so that we have a record.
