### ISSUE TITLE
Connect to HA using HTTP

### ISSUE THREAD

**Issue by TomerMir** [house-of-abbey/GarminHomeAssistant#201]
There is a way to connect to HA with HTTP using the Garmin API.
I found it [here](https://www.instructables.com/About-Communication-Between-Garmin-SDK-and-a-Raspb/).
If you're using Pi-Hole or other DNS server in your local network, you can set the domain `garmincdn.com` to the IP of your HA instance, this domain (along with some other domains) is whitelisted for communicating using HTTP.
I tested it using my Venu 2, and it worked :)

This solution is great for those who connect to their HA instance via VPN from the internet and don't want to create a public certificate for their server.

**Comment by philipabbey** [comment]
> I tested it using my Venu 2, and it worked

I've not had the chance to digest in full. It sounds like this issue is not about a code change to the watch app, but about a very specific infrastructure change to one's Raspberry Pi hosting Home Assistant. As such is actually out of scope of this open source project! Is that right?

The only effect I can see from this issue is perhaps some additional documentation added to https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md, or a specialist page in its own right?

If you would like to author that markdown file and contribute it to the project we can see about including it in the documentation. There are of course others who have asked about this problem and would be pleased to see a solution. As I have not (and don't have the inclination to) tried this, I'm not really in a position to write that up as a specific Garmin Home Assistant solution.

Are you interested in contributing this? Or it probably won't happen, we'll just link people to that article and close the issue!

Thank you.

**Comment by TomerMir** [comment]
I posted this because I think that for many users, the hardest step to setup this garmin app is to get HA working with HTTPS (without self singed certificate).
This is not an issue with the app, just a suggestion for a workaround that would help many newcomers.
This workaround is not specific to raspberry pi but to all self hosted instances of HA.
I wanted to post this workaround as an issue before adding a dedicated page to the documentation that explains how to use it.

**Comment by philipabbey** [comment]
I look forward to you pull request. Thank you!
