### ISSUE TITLE
App not showing up in glances on Vivoactive 5

### ISSUE THREAD

**Issue by Karstensson** [house-of-abbey/GarminHomeAssistant#48]
Hello,

I cannot manage to the the application to show up in the glances view on my vivoactive 5. I have checked the add more menu and it does not show up there. However it do show up in apps and recents menu. However if I download the widget version it does show up there. But then I need to have both apps installed. I guess that is not the expected behavior?

**Comment by jmcdermott683** [comment]
Hi. I'm also having the same problem - on venu 2.

**Comment by philipabbey** [comment]
> Hi. I'm also having the same problem - on venu 2.

Hmm, I have a Venu 2 and the application version does show up without having to configure the carousel. I can check the simulation (only) for the Vivaoactive 5 device. I've not got a lot to go on here...

**Comment by philipabbey** [comment]
![vivoactive5](https://github.com/house-of-abbey/GarminHomeAssistant/assets/24634527/4ee66d0e-68ad-45b8-a835-ceee20f44725)

Simulation on Vivoactive 5 seems to work fine, this is a screenshot from the simulator. Sorry to sound like I'm dodging the problem, I just can't debug the problem without the failure to pursue.

**Comment by philipabbey** [comment]
> I cannot manage to the the application to show up in the glances view on my vivoactive 5. I have checked the add more menu and it does not show up there. However it do show up in apps and recents menu. However if I download the widget version it does show up there. But then I need to have both apps installed. I guess that is not the expected behavior?

If it had not been for the loading of both the widget and the application versions, I would have suggested the widget version had been loaded by mistake instead of the application version. On an old Vivoactive 3 watch we've pressed back into action for testing, we have both the application and the widget versions installed side by side and both work fine. (Obviously the application is started from the application menu and has no glance.)

Please let us know if you figure out what the issue is.

**Comment by Karstensson** [comment]
Thanks for investigating at least. I got a new software update for my watch today. After installing the update the Homeassistant app automagically showd up in the glances view! So problem solved :-)
